// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "PythonKit",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "PythonKit",
            targets: ["AppModule"],
            bundleIdentifier: "me.Chu.Frank.PythonKit",
            teamIdentifier: "ST3F674BZF",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/pvieito/PythonKit.git", .branch("master"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)