# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouyinObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouyinObjc
  pod 'LookinServer', :configurations => ['Debug']
  pod 'SDWebImage', '~> 5.0'
  pod 'DoccDemo', :path => './DoccDemo'


  target 'DouyinObjcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouyinObjcUITests' do
    # Pods for testing
  end

end
